runtime:
  - MainRuntimeConfig:
      class: ru.taskurotta.spring.configs.RuntimeConfigPathXmlApplicationContext
      instance:
        context: ru/taskurotta/fir/client/RuntimeBeans.xml

spreader:
  - MainTaskSpreaderConfig:
      class: ru.taskurotta.spring.configs.SpreaderConfigPathXmlApplicationContext
      instance:
        context: ru/taskurotta/fir/client/SpreaderBeans.xml

profiler:
  - MainProfilerConfig:
      class: ru.taskurotta.bootstrap.config.DefaultProfilerConfig
      instance:
        class: ru.taskurotta.bootstrap.profiler.MetricsProfiler
        properties:
          meterCycle: true
          trackExecute: true
          trackCycle: true
          trackPull: true
          trackRelease: true
          trackError: true
          logOutput: true
          logOutputPeriod: 10
          consoleOutput: false
          consoleOutputPeriod: 10

policy:
  - MainPolicyConfig:
      class: ru.taskurotta.bootstrap.config.DefaultRetryPolicyConfig
      instance:
        class: ru.taskurotta.policy.retry.LinearRetryPolicy
        properties:
          initialRetryIntervalSeconds: 10
          maximumRetryIntervalSeconds: 300
          maximumAttempts: 100

actor:
  - FirPiDecider:
      actorInterface: ru.taskurotta.fir.client.deciders.FirDecider
      runtimeConfig: MainRuntimeConfig
      spreaderConfig: MainTaskSpreaderConfig
      profilerConfig: MainProfilerConfig
      count: 1

  - BusWorker:
      actorInterface: ru.taskurotta.fir.client.workers.BusWorker
      runtimeConfig: MainRuntimeConfig
      spreaderConfig: MainTaskSpreaderConfig
      profilerConfig: MainProfilerConfig
      count: 10

  - FirWorker:
        actorInterface: ru.taskurotta.fir.client.workers.FirWorker
        runtimeConfig: MainRuntimeConfig
        spreaderConfig: MainTaskSpreaderConfig
        profilerConfig: MainProfilerConfig
        count: 10

logback:
    appender:
        - STDOUT:
             key: name
             \@class: ch.qos.logback.core.ConsoleAppender
             encoder:
                 pattern: \%-4r [\%t] \%-5p \%c - \%m\%n
        - FILE:
             key: name
             \@class: ch.qos.logback.core.FileAppender
             file: ./logs/fir-client.log
             append: true
             encoder:
                 pattern: \%-4r [\%t] \%-5p \%c - \%m\%n
    logger:
        - ru.taskurotta:
             key: name
             \@level: DEBUG
        - org.springframework:
             key: name
             \@level: !!!str OFF
    root:
        appender-ref:
            - STDOUT:
                key: ref
            - FILE:
                key: ref

