runtime:
  - MainRuntimeConfig:
      instance:
        context: ru/taskurotta/recipes/parallel/RuntimeBeans.xml

spreader:
  - MainTaskSpreaderConfig:
      instance:
        context: ru/taskurotta/recipes/parallel/SpreaderBeans-hz.xml
        properties:
          cycles: 10
          accuracy: 1000

policy:
  - LinearRertyPolicyConfig:
      instance:
        class: ru.taskurotta.policy.retry.LinearRetryPolicy
        properties:
          initialRetryIntervalSeconds: 3
          maximumRetryIntervalSeconds: 30
          maximumAttempts: 3

actor:
  - PiDecider:
      actorInterface: ru.taskurotta.recipes.parallel.decider.PiDecider
      count: 1

  - PiWorker:
      actorInterface: ru.taskurotta.recipes.parallel.workers.PiWorker
      count: 10

logback:
    appender:
        - STDOUT:
             key: name
             \@class: ch.qos.logback.core.ConsoleAppender
             encoder:
                 pattern: \%d \%p [\%t] \%c - \%m\%n
        - FILE:
             key: name
             \@class: ch.qos.logback.core.FileAppender
             file: target/logs/recipes-parallel.log
             append: true
             encoder:
                 pattern: \%d \%p [\%t] \%c - \%m\%n
    logger:
        - ru.taskurotta:
             key: name
             \@level: INFO
        - ru.taskurotta.service.storage.GeneralTaskService:
            key: name
            \@level: DEBUG
        - org.springframework:
             key: name
             \@level: WARN
    root:
        appender-ref:
            - STDOUT:
                key: ref
            - FILE:
                key: ref

