#Location of Spring application context:
contextLocation: "classpath*:context/appContext.xml"

#Configuration of actors served by this server:
actorConfig:
  actorPreferences:
    - id: "default" #applied if actorId not found in config
      timeoutPolicies:
        TASK_START_TO_CLOSE: "TIMEOUT: 30 SECONDS" #TIMEOUT: prefix can be used to specify simple timeouts (template: "TIMEOUT: <int> <TimeUnit>")
        TASK_POLL_TO_COMMIT: "custom policy" #<-- MATCH
    - id: "some other actor" #Every real actor should be described here
      timeoutPolicies:
        TASK_START_TO_CLOSE: "TIMEOUT: 45 SECONDS"
#        TASK_POLL_TO_COMMIT: "timeout 15 seconds"

#List of expiration policies available for actors by name (new instance per actor):
  expirationPolicies:
    - name: "custom policy" #<-- MATCH
      className: "ru.taskurotta.server.config.expiration.impl.TimeoutWithFixedRetryPolicy"
      properties:
        timeout: 5
        timeUnit: "SECONDS"
        retry: 10

#Task server common properties (will be available as placeholders in spring context):
properties:
  db.url: "jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=ora1-vip.fccland.ru)(PORT=1531))(ADDRESS=(PROTOCOL=TCP)(HOST=ora2-vip.fccland.ru)(PORT=1531)))(CONNECT_DATA=(SERVICE_NAME=testext)))"
  db.user: "taskurotta"
  db.password: "taskurotta"
  retryTimes: 50 #retry for dependency graph modification
  recovery.schedule: "*/20 * * * * ?" #run recovery every 20 seconds
  recovery.period: 2 #recoveru scans for checkpoints created 1 day ago
  recovery.period.unit: "DAYS"
  recovery.timeStep: 12 #recovery time step | for monkey test with 10% failChance, recovery period should be covered in less then ~10 steps or it would fail forever
  recovery.timeStep.unit: "HOURS"


#Http server configuration:
logging:
    level: WARN
    loggers:
        ru.taskurotta: INFO
#        ru.taskurotta.backend.queue: DEBUG
#        ru.taskurotta.backend.task: DEBUG
        ru.taskurotta.backend: INFO
        ru.taskurotta.server.recovery: DEBUG
        com.yammer: INFO
    file:
        enabled: true
        archive: true
        currentLogFilename: ./target/logs/service.log
        archivedLogFilenamePattern: ./target/logs/service-%d.log.gz
http:
    gzip:
        enabled: false
    requestLog:
        file:
            enabled: true
            archive: true
            currentLogFilename: ./target/logs/requests.log
            archivedLogFilenamePattern: ./target/logs/service-%d.log.gz
#config can be extended here
#http://dropwizard.codahale.com/manual/core/#configuration-defaults