---
- name: 'Create mongodb data directory'
  tags:
  - start
  file: path={{ my_mongodb_path }} state=directory

- name: 'Start mongodb container'
  tags:
  - start
  docker:
    name: tsk_mongodb
    image: mongo:2.6.9
    state: reloaded
    net: bridge
    command: -f /etc/mongo/mongodb.conf
    volumes:
    - "{{ my_mongodb_path }}:/data/db"
    - "{{ my_mongodb_config }}:/etc/mongo/mongodb.conf"


- name: 'Stop mongodb container'
  tags:
  - stop
  docker:
    name: tsk_mongodb
    image: mongo:2.6.9
    state: stopped

- name: 'Remove mongodb container'
  tags:
  - clean
  docker:
    name: tsk_mongodb
    image: mongo:2.6.9
    state: absent

- name: 'Remove mongodb files'
  tags:
  - clean
  shell: "sudo rm -rf {{ my_mongodb_path }} removes={{ my_mongodb_path }}"
#  command: mv /path/to/foo /path/to/bar creates=/path/to/bar removes=/path/to/foo