runtime:
  - MainRuntimeConfig:
      class: ru.taskurotta.spring.configs.RuntimeConfigPathXmlApplicationContext
      instance:
        context: ru/taskurotta/recipes/retrypolicy/RuntimeBeans.xml

spreader:
  - MainTaskSpreaderConfig:
      class: ru.taskurotta.spring.configs.SpreaderConfigPathXmlApplicationContext
      instance:
        context: ru/taskurotta/recipes/retrypolicy/SpreaderBeans.xml
        properties:
          a: 1
          b: 2

actor:
  - SumDecider:
      actorInterface: ru.taskurotta.recipes.retrypolicy.decider.SumDecider
      runtimeConfig: MainRuntimeConfig
      spreaderConfig: MainTaskSpreaderConfig
      count: 1

  - PiWorker:
      actorInterface: ru.taskurotta.recipes.retrypolicy.workers.SumWorker
      runtimeConfig: MainRuntimeConfig
      spreaderConfig: MainTaskSpreaderConfig
      count: 10

logback:
    appender:
        - STDOUT:
             key: name
             \@class: ch.qos.logback.core.ConsoleAppender
             encoder:
                 pattern: \%-4r [\%t] \%-5p \%c - \%m\%n
        - FILE:
             key: name
             \@class: ch.qos.logback.core.FileAppender
             file: ./logs/recipes-retrypolicy.log
             append: true
             encoder:
                 pattern: \%-4r [\%t] \%-5p \%c - \%m\%n
    logger:
        - ru.taskurotta:
             key: name
             \@level: DEBUG
        - org.springframework:
             key: name
             \@level: !!!str OFF
    root:
        appender-ref:
            - STDOUT:
                key: ref
            - FILE:
                key: ref

