#Location of Spring application context:
contextLocation: "classpath*:context/appContext.xml"

#Configuration of actors served by this server:
actorConfig:
  actorPreferences:
    - id: "default"
      type: "default"
      timeoutPolicies:
        PROCESS_START_TO_CLOSE: "timeout 50 seconds"
        PROCESS_SCHEDULE_TO_START: "timeout 50 seconds"
        PROCESS_SCHEDULE_TO_CLOSE: "timeout 50 seconds"
        TASK_START_TO_CLOSE: "timeout 50 seconds"
        TASK_SCHEDULE_TO_START: "timeout 50 seconds"
        TASK_SCHEDULE_TO_CLOSE: "timeout 50 seconds"
        TASK_POLL_TO_COMMIT: "timeout 50 seconds"
        TASK_RELEASE_TO_COMMIT: "timeout 50 seconds"

#List of expiration policies available for actors: \\TODO: Should be parameterized somehow
  expirationPolicies:
    - name: "timeout 50 seconds"
      className: "ru.taskurotta.server.config.expiration.impl.TimeoutPolicy"
      properties:
        timeout: 50
        timeUnit: "SECONDS"
    - name: "retriable 60 seconds timeout"
      className: "ru.taskurotta.server.config.expiration.impl.TimeoutWithFixedRetryPolicy"
      properties:
        timeout: 60
        timeUnit: "SECONDS"
        retry: 10

#Task server common properties (will be available as placeholders in spring context):
properties:
  pollDelay: 2
  pollDelayUnit: "SECONDS"
  retryTimes: 10
  schedule.fast: "20 SECONDS"
  schedule.normal: "40 SECONDS"
  schedule.slow: "100 SECONDS"
  recovery.period: 60
  recovery.period.unit: "SECONDS"
  recovery.timeStep: 200
  recovery.timeStep.unit: "MILLISECONDS"

#Http server configuration:
logging:
    level: WARN
    loggers:
        ru.taskurotta: DEBUG
        com.yammer: INFO
    file:
        enabled: true
        currentLogFilename: ./target/logs/requests.log
        archivedLogFilenamePattern: ./target/logs/requests-%d.log.gz
