contextLocation: "classpath*:context/appContext.xml"
serverConfig:
  actorConfigs:
    - actorName: "first"
      timeout: -1
      expirationPolicy: "none"
    - actorName: "second"
      timeout: -1
      expirationPolicy: "error"
internalPoolConfig:
  poolSize: 100
  threadTimeout: 2000
properties:
  pollDelay: 1
  expirationCheckSchedule: "30 SECONDS"  
logging:
    level: WARN
    loggers:
        ru.taskurotta: DEBUG
        com.yammer: INFO
    file:
        enabled: true
        currentLogFilename: ./target/logs/requests.log
        archivedLogFilenamePattern: ./target/logs/requests-%d.log.gz
