contextLocation: "classpath*:context/appContext.xml"
actorConfig:
  actorPreferences:
    - name: "default"
      version: "default"
      expirationPolicy:
        className: "ru.taskurotta.server.config.expiration.FixedRetryPolicy"
        properties:
          retry: 50
          timeout: 1
          timeUnit: "SECONDS"
properties:
  pollDelay: 1
  expirationCheckSchedule: "50 SECONDS"
  expirationCheckLimit: 100
logging:
    level: WARN
    loggers:
        ru.taskurotta: DEBUG
        com.yammer: INFO
    file:
        enabled: true
        currentLogFilename: ./target/logs/requests.log
        archivedLogFilenamePattern: ./target/logs/requests-%d.log.gz
