contextLocation: "classpath*:context/appContext.xml"

actorConfig:
  actorPreferences:
    - id: "default"
      type: "default"
      expirationPolicy:
        className: "ru.taskurotta.server.config.expiration.FixedRetryPolicy"
        properties:
          retry: 50
          timeout: 1
          timeUnit: "SECONDS"

properties:
  pollDelay: 2
  pollDelayUnit: "SECONDS"
  retryTimes: 10
  recovery.task_start_to_close.schedule: "50 SECONDS"
  recovery.task_start_to_close.period: 60
  recovery.task_start_to_close.period_unit: "SECONDS"
  recovery.task_start_to_close.time_step: 200
  recovery.task_start_to_close.time_step_unit: "MILLISECONDS"

logging:
    level: WARN
    loggers:
        ru.taskurotta: DEBUG
        com.yammer: INFO
    file:
        enabled: true
        currentLogFilename: ./target/logs/requests.log
        archivedLogFilenamePattern: ./target/logs/requests-%d.log.gz
