runtime:
  - MainRuntimeConfig:
      class: ru.taskurotta.spring.configs.RuntimeConfigPathXmlApplicationContext
      instance:
        context: ru/taskurotta/recipes/calculate/RuntimeBeans.xml
        properties:
          sleep: -1 #-1 = disabled
          workerFailChance: -1 #-1 = disabled
          deciderFailChance: -1 #-1 = disabled
          varyExceptions: true


spreader:
  - MainTaskSpreaderConfig:
      class: ru.taskurotta.spring.configs.SpreaderConfigPathXmlApplicationContext
      instance:
        context: ru/taskurotta/recipes/calculate/SpreaderBeans-jersey.xml
        properties:
          count: 10
          startTasks: true
          startTasksInBackground: true
          startTaskPeriodSeconds: -1 #-1 = disabled
          endpoint: "http://localhost:8811"
          threadPoolSize: 10
          readTimeout: 0
          connectTimeout: 3000
          waitOnEveryNTaskOnStart: 1000 #-1 = disabled
          waitWorSecondsOnStart: 3600 #-1 = disabled


policy:
  - MainPolicyConfig:
      class: ru.taskurotta.bootstrap.config.DefaultRetryPolicyConfig
      instance:
        class: ru.taskurotta.policy.retry.LinearRetryPolicy
        properties:
          initialRetryIntervalSeconds: 1
          maximumRetryIntervalSeconds: 10
          maximumAttempts: 3

profiler:
  - MainProfilerConfig:
      class: ru.taskurotta.bootstrap.profiler.impl.RollingLoggingProfilerConfig
      instance:
        singleton: true
        logPeriod: 10000

actor:
  - MathActionDecider:
      actorInterface: ru.taskurotta.recipes.calculate.decider.MathActionDecider
      runtimeConfig: MainRuntimeConfig
      spreaderConfig: MainTaskSpreaderConfig
      profilerConfig: MainProfilerConfig
      policyConfig: MainPolicyConfig
      count: 4
#      properties:
#        failover: "5 SECONDS"

  - Multiplier:
      actorInterface: ru.taskurotta.recipes.calculate.worker.Multiplier
      runtimeConfig: MainRuntimeConfig
      spreaderConfig: MainTaskSpreaderConfig
      profilerConfig: MainProfilerConfig
      policyConfig: MainPolicyConfig
      count: 2
#      properties:
#        failover: "25 SECONDS"

  - NumberGenerator:
      actorInterface: ru.taskurotta.recipes.calculate.worker.NumberGenerator
      runtimeConfig: MainRuntimeConfig
      spreaderConfig: MainTaskSpreaderConfig
      profilerConfig: MainProfilerConfig
      policyConfig: MainPolicyConfig
      count: 4
#      properties:
#        failover: "25 SECONDS"

  - Summarizer:
      actorInterface: ru.taskurotta.recipes.calculate.worker.Summarizer
      runtimeConfig: MainRuntimeConfig
      spreaderConfig: MainTaskSpreaderConfig
      profilerConfig: MainProfilerConfig
      policyConfig: MainPolicyConfig
      count: 2
#      properties:
#        failover: "25 SECONDS"