runtime:
  - MainRuntimeConfig:
      class: ru.taskurotta.spring.configs.RuntimeConfigPathXmlApplicationContext
      instance:
        context: ru/taskurotta/recipes/calculate/RuntimeBeans.xml
        properties:
          sleep: -1
          failChance: 0.3
          varyExceptions: true

spreader:
  - MainTaskSpreaderConfig:
      class: ru.taskurotta.spring.configs.SpreaderConfigPathXmlApplicationContext
      instance:
        context: ru/taskurotta/recipes/calculate/SpreaderBeans.xml
        properties:
          count: 15
          loggingPeriod: 10000
          taskPollDelay: 1
          count: 100
          startTasks: true
          startTasksInBackground: true
          startTaskPeriodSeconds: -1
          endpoint: "http://localhost:8811"
          threadPoolSize: 30
          readTimeout: 0
          connectTimeout: 3000

profiler:
  - MainProfilerConfig:
      class: ru.taskurotta.bootstrap.profiler.impl.RollingLoggingProfilerConfig
      instance:
        singleton: true
        logPeriod: 6000

actor:
  - MathActionDecider:
      actorInterface: ru.taskurotta.recipes.calculate.decider.MathActionDecider

  - Multiplier:
      actorInterface: ru.taskurotta.recipes.calculate.worker.Multiplier

  - NumberGenerator:
      actorInterface: ru.taskurotta.recipes.calculate.worker.NumberGenerator

  - Summarizer:
      actorInterface: ru.taskurotta.recipes.calculate.worker.Summarizer
