runtime:
  - rtMain:
      class: ru.taskurotta.spring.configs.RuntimeConfigPathXmlApplicationContext
      instance:
        context: ru/taskurotta/recipes/calculate/RuntimeBeans.xml
        properties:
          sleep: -1 #-1 = disabled
          workerFailChance: -1 #-1 = disabled
          deciderFailChance: -1 #-1 = disabled
          varyExceptions: true


spreader:
  - rtMain:
      class: ru.taskurotta.spring.configs.SpreaderConfigPathXmlApplicationContext
      instance:
        context: ru/taskurotta/recipes/calculate/SpreaderBeans-jersey.xml
        properties:
          count: 50
          startTasks: true
          startTasksInBackground: true
          startTaskPeriodSeconds: 60 #-1 = disabled
          endpoint: "http://localhost:8811"
          threadPoolSize: 10
          readTimeout: 0
          connectTimeout: 3000
          waitOnEveryNTask: -1 #-1 = disabled
          waitOnEveryNTaskInSeconds: -1 #-1 = disabled


policy:
  - MainPolicyConfig:
      class: ru.taskurotta.bootstrap.config.DefaultRetryPolicyFactory
      instance:
        class: ru.taskurotta.policy.retry.LinearRetryPolicy
        properties:
          initialRetryIntervalSeconds: 1
          maximumRetryIntervalSeconds: 1
          maximumAttempts: 99

profiler:
  - MainProfilerConfig:
      class: ru.taskurotta.bootstrap.profiler.impl.RollingLoggingProfilerConfig
      instance:
        singleton: true
        logPeriod: 30000

actor:
  - MathActionDecider:
      actorInterface: ru.taskurotta.recipes.calculate.decider.MathActionDecider
#      count: 4
#      properties:
#        failover: "5 SECONDS"

  - Multiplier:
      actorInterface: ru.taskurotta.recipes.calculate.worker.Multiplier
#      count: 2
#      properties:
#        failover: "25 SECONDS"

  - NumberGenerator:
      actorInterface: ru.taskurotta.recipes.calculate.worker.NumberGenerator
#      count: 4
#      properties:
#        failover: "25 SECONDS"

  - Summarizer:
      actorInterface: ru.taskurotta.recipes.calculate.worker.Summarizer
#      count: 2
#      properties:
#        failover: "25 SECONDS"


logback:
    appender:
        - STDOUT:
             key: name
             \@class: ch.qos.logback.core.ConsoleAppender
             encoder:
                 pattern: \%d [\%t] \%-5p \%c - \%m\%n
        - FILE:
             key: name
             \@class: ch.qos.logback.core.FileAppender
             file: ./target/logs/recipes-calculate.log
             append: true
             encoder:
                 pattern: \%d [\%t] \%-5p \%c - \%m\%n
    logger:
        - ru.taskurotta:
             key: name
             \@level: INFO
        - ru.taskurotta.bootstrap.pool:
             key: name
             \@level: INFO
        - ru.taskurotta.recipes.calculate:
            key: name
            \@level: INFO
        - com.hazelcast:
              key: name
              \@level: WARN
        - org.apache.commons.httpclient:
              key: name
              \@level: WARN
        - httpclient.wire:
              key: name
              \@level: WARN
        - org.springframework:
             key: name
             \@level: WARN
    root:
        appender-ref:
            - STDOUT:
                key: ref
#            - FILE:
#                key: ref

