contextLocation: "classpath*:context/appContext.xml"
properties:
  pollDelay: 1  
logging:
    level: WARN
    loggers:
        ru.taskurotta: INFO
        com.yammer: INFO
    file:
        enabled: true
        currentLogFilename: ./target/logs/requests.log
        archivedLogFilenamePattern: ./target/logs/requests-%d.log.gz
