version: "2"

services:
  tsk_mongodb:
    container_name: tsk_mongodb
    networks:
      - taskurotta
    image: mongo:3.2.0
    volumes:
      - ./data/mongo:/data/db
      - ./etc/mongo:/etc/mongo
    command: -f /etc/mongo/mongodb.conf

  tsk_node1: &tsk_node
    container_name: tsk_node1
    hostname: tsk_node1
    networks:
      - taskurotta
    image: taskurotta/server
    volumes:
      - ./data/node1:/tmp/javadumps
      - ./data/node1:/var/log/taskurotta
      - ./etc/node:/etc/taskurotta/server
    links:
      - tsk_mongodb
    command: |
      java -Xmx512m -Xms512m -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/tmp/javadumps
      -Dhazelcast.health.monitoring.level=OFF -server -jar /opt/taskurotta/taskurotta.jar server
      /etc/taskurotta/server/config.yml

#  tsk_node2:
#    <<: *tsk_node
#    container_name: tsk_node2
#    hostname: tsk_node2
#    volumes:
#      - ./data/node2:/tmp/javadumps
#      - ./data/node2:/var/log/taskurotta
#      - ./etc/node:/etc/taskurotta/server

  tsk_http:
    container_name: tsk_http
    networks:
      - taskurotta
    image: haproxy:1.6.2
    volumes:
      - ./etc/haproxy/haproxy.conf:/usr/local/etc/haproxy/haproxy.cfg
      - ./data/haproxy:/var/log/haproxy
    links:
      - tsk_node1
#      - tsk_node2
    expose:
      - 80
    ports:
      - "80:80"

networks:
  taskurotta:
    driver: bridge