version: "2"

services:
  tsk_node1: &tsk_node
    volumes:
      - ../taskurotta/target/taskurotta-$MVN_PROJECT_VERSION.jar:/opt/taskurotta/taskurotta.jar

#  tsk_node2:
#    <<: *tsk_node

  tsk_web_dev:
    container_name: tsk_web_dev
    networks:
      - taskurotta
    image: python:2.7.11
    volumes:
      - ../dropwizard/src/main/resources/assets:/www
    command: bash -c "cd www && python -m SimpleHTTPServer 8080"

  tsk_web_doc_dev:
    container_name: tsk_web_doc_dev
    networks:
      - taskurotta
    image: python:2.7.11
    volumes:
      - ../documentation/target/classes/assets:/www
    command: bash -c "cd www && python -m SimpleHTTPServer 8080"

  tsk_http:
    volumes:
      - ./etc/haproxy/haproxy_dev.conf:/usr/local/etc/haproxy/haproxy.cfg
    links:
      - tsk_node1
#      - tsk_node2
      - tsk_web_dev
      - tsk_web_doc_dev
