runtime:
  - MainRuntimeConfig:
      class: ru.taskurotta.spring.configs.RuntimeConfigPathXmlApplicationContext
      instance:
        context: ru/taskurotta/restarter/RuntimeBeans.xml
        properties:
          processBatchSize: 100
          taskBatchSize: 10
          dependencyBackend.retryTimes: 10
          db.url: "jdbc:oracle:thin:@(DESCRIPTION = (ADDRESS = (PROTOCOL = TCP)(HOST = db1.fccland.ru)(PORT = 1521))(CONNECT_DATA = (SERVER = DEDICATED)(SERVICE_NAME = orcl.fccland.ru)))"
          db.user: "taskurotta"
          db.password: "taskurotta"
          db.validating: true  #validate queues existence in DB
          db.autocreating: true #auto create new queues in DB if there are no explicitly configured
          queueBackend.pollDaley: 60
          queueBackend.pollDelayUnit: SECONDS

spreader:
  - MainTaskSpreaderConfig:
      class: ru.taskurotta.spring.configs.SpreaderConfigPathXmlApplicationContext
      instance:
        context: ru/taskurotta/restarter/SpreaderBeans.xml
        properties:
          cycles: 10
          accuracy: 1000

profiler:
  - MainProfilerConfig:
      class: ru.taskurotta.bootstrap.config.DefaultProfilerConfig
      instance:
        class: ru.taskurotta.bootstrap.profiler.MetricsProfiler
        properties:
          meterCycle: true
          trackExecute: true
          trackCycle: false
          trackPull: true
          trackRelease: true
          trackError: false
          logOutput: false
          logOutputPeriod: 10
          consoleOutput: false
          consoleOutputPeriod: 10

policy:
  - LinearRertyPolicyConfig:
      class: ru.taskurotta.bootstrap.config.DefaultRetryPolicyConfig
      instance:
        class: ru.taskurotta.policy.retry.LinearRetryPolicy
        properties:
          initialRetryIntervalSeconds: 3
          maximumRetryIntervalSeconds: 30
          maximumAttempts: 3

actor:
  - Coordinator:
      actorInterface: ru.taskurotta.restarter.deciders.Coordinator
      runtimeConfig: MainRuntimeConfig
      spreaderConfig: MainTaskSpreaderConfig
      profilerConfig: MainProfilerConfig
      policyConfig: LinearRertyPolicyConfig
      count: 1

  - Analyzer:
      actorInterface: ru.taskurotta.restarter.workers.Analyzer
      runtimeConfig: MainRuntimeConfig
      spreaderConfig: MainTaskSpreaderConfig
      profilerConfig: MainProfilerConfig
      policyConfig: LinearRertyPolicyConfig
      count: 1

  - Restarter:
      actorInterface: ru.taskurotta.restarter.workers.Restarter
      runtimeConfig: MainRuntimeConfig
      spreaderConfig: MainTaskSpreaderConfig
      profilerConfig: MainProfilerConfig
      policyConfig: LinearRertyPolicyConfig
      count: 10

logback:
    appender:
        - STDOUT:
             key: name
             \@class: ch.qos.logback.core.ConsoleAppender
             encoder:
                 pattern: \%-4r \%d [\%t] \%-5p \%c - %m%n
        - FILE:
             key: name
             \@class: ch.qos.logback.core.FileAppender
             file: ./logs/restarter.log
             append: true
             encoder:
                 pattern: \%-4r \%d [\%t] \%-5p \%c - %m%n
    logger:
        - ru.taskurotta:
             key: name
             \@level: INFO
        - ru.taskurotta.restarter:
             key: name
             \@level: DEBUG
        - org.springframework:
             key: name
             \@level: !!!str OFF
    root:
        appender-ref:
            - STDOUT:
                key: ref
            - FILE:
                key: ref

