runtime:
  - MainRuntimeConfig:
      class: ru.taskurotta.spring.configs.RuntimeConfigPathXmlApplicationContext
      instance:
        context: ru/taskurotta/recipes/custom/RuntimeBeans.xml

spreader:
  - MainTaskSpreaderConfig:
      class: ru.taskurotta.spring.configs.SpreaderConfigPathXmlApplicationContext
      instance:
        context: ru/taskurotta/recipes/custom/SpreaderBeans.xml
        properties:
          a: 1
          b: 2

actor:
  - CustomDecider:
      actorInterface: ru.taskurotta.recipes.custom.deciders.CustomDecider
      runtimeConfig: MainRuntimeConfig
      spreaderConfig: MainTaskSpreaderConfig
      count: 1

  - DescendantCustomDecider:
        actorInterface: ru.taskurotta.recipes.custom.deciders.DescendantCustomDecider
        runtimeConfig: MainRuntimeConfig
        spreaderConfig: MainTaskSpreaderConfig
        count: 1

  - CustomWorker:
      actorInterface: ru.taskurotta.recipes.custom.workers.CustomWorker
      runtimeConfig: MainRuntimeConfig
      spreaderConfig: MainTaskSpreaderConfig
      count: 1

logback:
    appender:
        - STDOUT:
             key: name
             \@class: ch.qos.logback.core.ConsoleAppender
             encoder:
                 pattern: \%-4r [\%t] \%-5p \%c - \%m\%n
        - FILE:
             key: name
             \@class: ch.qos.logback.core.FileAppender
             file: ./logs/recipes-custom.log
             append: true
             encoder:
                 pattern: \%-4r [\%t] \%-5p \%c - \%m\%n
    logger:
        - ru.taskurotta:
             key: name
             \@level: DEBUG
        - org.springframework:
             key: name
             \@level: !!!str OFF
    root:
        appender-ref:
            - STDOUT:
                key: ref
            - FILE:
                key: ref

