runtime:
  - MainRuntimeConfig:
      class: ru.taskurotta.spring.configs.RuntimeConfigPathXmlApplicationContext
      instance:
        context: ru/taskurotta/example/calculate/RuntimeBeans.xml
        properties:
          sleep: -1
          failChance: 0.0


spreader:
  - MainTaskSpreaderConfig:
      class: ru.taskurotta.spring.configs.SpreaderConfigPathXmlApplicationContext
      instance:
        context: ru/taskurotta/example/calculate/SpreaderBeans-jersey.xml
        properties:
          count: 100
          startTasks: true
          startTasksInBackground: false
          endpoint: "http://localhost:8080"
          threadPoolSize: 15
          readTimeout: 0
          connectTimeout: 3000

policy:
  - MainPolicyConfig:
      class: ru.taskurotta.bootstrap.config.DefaultRetryPolicyConfig
      instance:
        class: ru.taskurotta.policy.retry.LinearRetryPolicy
        properties:
          initialRetryIntervalSeconds: 1
          maximumRetryIntervalSeconds: 10
          maximumAttempts: 3

profiler:
  - MainProfilerConfig:
      class: ru.taskurotta.bootstrap.profiler.impl.RollingLoggingProfilerConfig
      instance:
        singleton: true
        logPeriod: 30000

actor:
  - MathActionDecider:
      actorInterface: ru.taskurotta.example.calculate.decider.MathActionDecider
      runtimeConfig: MainRuntimeConfig
      spreaderConfig: MainTaskSpreaderConfig
      profilerConfig: MainProfilerConfig
      policyConfig: MainPolicyConfig
      count: 1
      properties:
        failover: "10 SECONDS"

  - Multiplier:
      actorInterface: ru.taskurotta.example.calculate.worker.Multiplier
      runtimeConfig: MainRuntimeConfig
      spreaderConfig: MainTaskSpreaderConfig
      profilerConfig: MainProfilerConfig
      policyConfig: MainPolicyConfig
      count: 1
      properties:
        failover: "10 SECONDS"

  - NumberGenerator:
      actorInterface: ru.taskurotta.example.calculate.worker.NumberGenerator
      runtimeConfig: MainRuntimeConfig
      spreaderConfig: MainTaskSpreaderConfig
      profilerConfig: MainProfilerConfig
      policyConfig: MainPolicyConfig
      count: 5
      properties:
        failover: "10 SECONDS"

  - Summarizer:
      actorInterface: ru.taskurotta.example.calculate.worker.Summarizer
      runtimeConfig: MainRuntimeConfig
      spreaderConfig: MainTaskSpreaderConfig
      profilerConfig: MainProfilerConfig
      policyConfig: MainPolicyConfig
      count: 1
      properties:
        failover: "10 SECONDS"