runtime:
  - MainRuntimeConfig:
      class: ru.taskurotta.spring.configs.RuntimeConfigPathXmlApplicationContext
      instance:
        context: ru/taskurotta/example/calculate/RuntimeBeans.xml
        properties:
          sleep: -1
          failChance: 0.0


spreader:
  - MainTaskSpreaderConfig:
      class: ru.taskurotta.spring.configs.SpreaderConfigPathXmlApplicationContext
      instance:
        context: ru/taskurotta/example/calculate/SpreaderBeans-jersey.xml
        properties:
          count: 185
          endpoint: "http://localhost:8080"
          threadPoolSize: 10
          readTimeout: 3000
          connectTimeout: 3000
          loggerPeriod: 8000
          maxConnectionsPerHost: 10

profiler:
  - MainProfilerConfig:
      class: ru.taskurotta.bootstrap.profiler.impl.RollingLoggingProfilerConfig
      instance:
        singleton: true
        logPeriod: 6000

actor:
  - MathActionDecider:
      actorInterface: ru.taskurotta.example.calculate.decider.MathActionDecider
      runtimeConfig: MainRuntimeConfig
      spreaderConfig: MainTaskSpreaderConfig
      profilerConfig: MainProfilerConfig
      count: 5

  - Multiplier:
      actorInterface: ru.taskurotta.example.calculate.worker.Multiplier
      runtimeConfig: MainRuntimeConfig
      spreaderConfig: MainTaskSpreaderConfig
      profilerConfig: MainProfilerConfig
      count: 2

  - NumberGenerator:
      actorInterface: ru.taskurotta.example.calculate.worker.NumberGenerator
      runtimeConfig: MainRuntimeConfig
      spreaderConfig: MainTaskSpreaderConfig
      profilerConfig: MainProfilerConfig
      count: 2

  - Summarizer:
      actorInterface: ru.taskurotta.example.calculate.worker.Summarizer
      runtimeConfig: MainRuntimeConfig
      spreaderConfig: MainTaskSpreaderConfig
      profilerConfig: MainProfilerConfig
      count: 2