---
- name: 'Create nginx log directory'
  tags:
  - start
  file: path={{ nginx_path }} state=directory

- name: 'Generate nginx config file'
  tags:
  - start
  template: src=nginx.conf.j2 dest={{ nginx_config }}

- name: 'Start nginx container'
  tags:
  - start
  docker:
    name: tsk_nginx
    image: nginx:1.9.6
    state: reloaded
    net: bridge
    volumes:
    - "{{ nginx_path }}:/var/log/nginx"
    - "{{ nginx_config }}:/etc/nginx/nginx.conf"
    ports:
    - "80:80"

- name: 'Stop nginx container'
  tags:
  - stop
  docker:
    name: tsk_nginx
    image: nginx:1.9.6
    state: stopped

- name: 'Remove nginx container'
  tags:
  - clean
  docker:
    name: tsk_nginx
    image: nginx:1.9.6
    state: absent

- name: 'Remove nginx files'
  tags:
  - clean
  shell: "sudo rm -rf {{ nginx_path }} removes={{ nginx_path }}"
#  command: mv /path/to/foo /path/to/bar creates=/path/to/bar removes=/path/to/foo