runtime:
  - MainRuntimeConfig:
      class: ru.taskurotta.spring.configs.RuntimeConfigPathXmlApplicationContext
      instance:
        context: ru/taskurotta/recipes/stress/RuntimeBeans.xml

spreader:
  - MainTaskSpreaderConfig:
      class: ru.taskurotta.spring.configs.SpreaderConfigPathXmlApplicationContext
      instance:
        context: ru/taskurotta/recipes/stress/SpreaderBeans-jersey.xml
        properties:
          endpoint: "http://localhost:8811"
          threadPoolSize: 100
          readTimeout: 0
          connectTimeout: 3000
          cycles: 10
          initialCount: 8
          shotSize: 4000
          needRun: true

profiler:
  - MainProfilerConfig:
      class: ru.taskurotta.bootstrap.config.DefaultProfilerConfig
      instance:
        class: ru.taskurotta.recipes.stress.LifetimeProfiler
        properties:
          exitAfterAll: false
          tasksForStat: 500

actor:
  - MultiplierDecider:
      actorInterface: ru.taskurotta.recipes.multiplier.MultiplierDecider
      runtimeConfig: MainRuntimeConfig
      spreaderConfig: MainTaskSpreaderConfig
      profilerConfig: MainProfilerConfig
      count: 20

logback:
    appender:
        - STDOUT:
             key: name
             \@class: ch.qos.logback.core.ConsoleAppender
             encoder:
                 pattern: \%c - \%m\%n
        - FILE:
             key: name
             \@class: ch.qos.logback.core.FileAppender
             file: ./target/logs/recipes-multiply.log
             append: true
             encoder:
                 pattern: \%-4r [\%t] \%-5p \%c - \%m\%n
    logger:
        - ru.taskurotta:
             key: name
             \@level: !!!str OFF
        - ru.taskurotta.recipes.stress:
             key: name
             \@level: DEBUG
        - org:
             key: name
             \@level: !!!str OFF
        - httpclient:
             key: name
             \@level: !!!str OFF
    root:
        appender-ref:
            - STDOUT:
                key: ref
            - FILE:
                key: ref

