runtime:
  - MainRuntimeConfig:
      class: ru.taskurotta.spring.configs.RuntimeConfigPathXmlApplicationContext
      instance:
        context: example2/RuntimeBeansExample2.xml
        properties:
          sleep: -1

spreader:
  - MainTaskSpreaderConfig:
      class: ru.taskurotta.spring.configs.SpreaderConfigPathXmlApplicationContext
      instance:
        context: example2/SpreaderBeansExample2.xml
        properties:
          count: 10

actor:
  - MathActionDecider:
      actorInterface: ru.taskurotta.example.calculate.decider.MathActionDecider
      runtimeConfig: MainRuntimeConfig
      spreaderConfig: MainTaskSpreaderConfig
      count: 1

  - Multiplier:
      actorInterface: ru.taskurotta.example.calculate.worker.Multiplier
      runtimeConfig: MainRuntimeConfig
      spreaderConfig: MainTaskSpreaderConfig
      count: 1

  - NumberGenerator:
      actorInterface: ru.taskurotta.example.calculate.worker.NumberGenerator
      runtimeConfig: MainRuntimeConfig
      spreaderConfig: MainTaskSpreaderConfig
      count: 1

  - Summarizer:
      actorInterface: ru.taskurotta.example.calculate.worker.Summarizer
      runtimeConfig: MainRuntimeConfig
      spreaderConfig: MainTaskSpreaderConfig
      count: 1